brokerClusterName=ZhikexingCluster
brokerName=zhikexing-broker-a
brokerId=0
namesrvAddr=rocketmq-nameserver:9876
listenPort=10911
deleteWhen=04
fileReservedTime=168
brokerRole=ASYNC_MASTER
flushDiskType=SYNC_FLUSH
autoCreateTopicEnable=false
autoCreateSubscriptionGroup=false
enableTopicMessageTypeCheck=true
transactionTimeOut=6000
transactionCheckInterval=10000
transactionCheckMax=30
metricsExporterType=PROM
metricsPromExporterPort=5557
metricsPromExporterHost=0.0.0.0
